import type { CaptionVariant, SubtitleChunk, SubtitleStyle, TranscriptWord } from '../types'
import { cleanCaptionText, resolveChunkStyle, resolveWordStyle } from './transcription'

export type AssPalette = 'normal' | 'mask'

export type BuildAssOptions = {
  chunks: SubtitleChunk[]
  style: SubtitleStyle
  variants?: CaptionVariant[]
  width: number
  height: number
  palette?: AssPalette
}

type WordLine = TranscriptWord[]

type ChunkLayout = {
  scale: number
  maxWidth: number
  padding: number
  fittedFontSize: number
  lines: WordLine[]
  x: number
  textX: number
  y: number
}

export function buildAssDocument({
  chunks,
  style,
  variants = [],
  width,
  height,
  palette = 'normal',
}: BuildAssOptions) {
  const safeWidth = evenDimension(width || 1920)
  const safeHeight = evenDimension(height || 1080)
  const styleEntries = buildStyleEntries(style, variants)
  const styleMap = new Map(styleEntries.map((entry) => [entry.id, entry.name]))
  const styles = styleEntries
    .map((entry) => styleToAss(entry.name, entry.style, safeWidth, safeHeight, palette))
    .join('\n')
  const events = chunks
    .filter((chunk) => chunk.text.trim() && chunk.end > chunk.start)
    .flatMap((chunk) =>
      chunkToEvents(
        chunk,
        resolveChunkStyle(style, variants, chunk),
        styleMap.get(chunk.variantId ?? 'main') ?? styleMap.get('main') ?? 'Main',
        safeWidth,
        safeHeight,
        palette,
      ),
    )
    .join('\n')

  return `[Script Info]
; Generated by KareMetin Desktop
ScriptType: v4.00+
PlayResX: ${safeWidth}
PlayResY: ${safeHeight}
ScaledBorderAndShadow: yes
WrapStyle: 2
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
${styles}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
${events}
`
}

function buildStyleEntries(style: SubtitleStyle, variants: CaptionVariant[]) {
  const entries = [{ id: 'main', name: 'Main', style }]
  for (const variant of variants) {
    if (variant.id === 'main') {
      entries[0] = { id: 'main', name: 'Main', style: variant.style }
      continue
    }
    entries.push({ id: variant.id, name: assStyleName(variant.name, entries.length), style: variant.style })
  }
  return entries
}

function styleToAss(name: string, style: SubtitleStyle, width: number, height: number, palette: AssPalette) {
  const scale = height / 1080
  const fontSize = Math.max(10, style.fontSize * scale)
  const textColor = palette === 'mask' ? '#ffffff' : style.textColor
  const activeColor = palette === 'mask' ? '#ffffff' : style.activeColor
  const outlineColor = palette === 'mask' ? '#ffffff' : style.strokeColor
  const backgroundColor = palette === 'mask' ? '#000000' : style.backgroundColor
  const backgroundOpacity = palette === 'mask' ? 0 : style.backgroundOpacity
  const borderStyle = 1
  const outline = Math.max(0, style.strokeWidth * scale)
  const shadow = style.shadow && palette === 'normal' ? Math.max(0, style.shadowOffsetY * scale) : 0
  const spacing = style.letterSpacing * scale
  const backAlpha = 1 - Math.min(1, Math.max(0, backgroundOpacity))

  return [
    `Style: ${name}`,
    assFont(style.fontFamily),
    decimal(fontSize),
    assColor(textColor),
    assColor(activeColor),
    assColor(outlineColor),
    assColor(backgroundColor, backAlpha),
    style.fontWeight >= 700 ? '-1' : '0',
    style.italic ? '-1' : '0',
    '0',
    '0',
    '100',
    '100',
    decimal(spacing),
    '0',
    String(borderStyle),
    decimal(outline),
    decimal(shadow),
    '5',
    String(Math.round(width * 0.03)),
    String(Math.round(width * 0.03)),
    String(Math.round(height * 0.03)),
    '1',
  ].join(',')
}

function chunkToEvents(
  chunk: SubtitleChunk,
  style: SubtitleStyle,
  styleName: string,
  width: number,
  height: number,
  palette: AssPalette,
) {
  const words = chunk.words.length ? [...chunk.words].sort((a, b) => a.start - b.start) : []
  const hasDynamicWords =
    words.length > 0 &&
    (style.highlightActiveWord || style.wordTransition !== 'none' || words.some((word) => Boolean(word.style)))
  const backgroundEvents =
    style.backgroundMode !== 'none' && palette === 'normal'
      ? [eventLine(chunk.start, chunk.end, styleName, renderCaptionBackground(chunk, style, width, height), 0)]
      : []

  if (!hasDynamicWords) {
    return [
      ...backgroundEvents,
      eventLine(
        chunk.start,
        chunk.end,
        styleName,
        renderChunk(chunk, style, undefined, width, height, palette, true, true, chunk.end - chunk.start),
        1,
      ),
    ]
  }

  const boundaries = Array.from(
    new Set([
      chunk.start,
      ...words.flatMap((word) => [clamp(word.start, chunk.start, chunk.end), clamp(word.end, chunk.start, chunk.end)]),
      chunk.end,
    ]),
  ).sort((a, b) => a - b)
  const intervals = boundaries
    .slice(0, -1)
    .map((start, index) => ({ start, end: boundaries[index + 1] }))
    .filter((interval) => interval.end - interval.start >= 0.005)
  const events = intervals.map((interval, index) => {
    const midpoint = interval.start + (interval.end - interval.start) / 2
    const activeWord = words.find((word) => midpoint >= word.start && midpoint < word.end)
    return eventLine(
      interval.start,
      interval.end,
      styleName,
      renderChunk(
        chunk,
        style,
        activeWord?.id,
        width,
        height,
        palette,
        index === 0,
        index === intervals.length - 1,
        interval.end - interval.start,
      ),
      1,
    )
  })
  return [...backgroundEvents, ...events]
}

function renderChunk(
  chunk: SubtitleChunk,
  style: SubtitleStyle,
  activeWordId: string | undefined,
  width: number,
  height: number,
  palette: AssPalette,
  includeTransitionIn: boolean,
  includeTransitionOut: boolean,
  eventDuration: number,
) {
  const layout = layoutChunk(chunk, style, width, height)
  const alignment = style.align === 'left' ? 4 : style.align === 'right' ? 6 : 5
  const durationMs = Math.max(1, Math.round(eventDuration * 1000))
  const fadeIn = includeTransitionIn && style.transitionIn === 'fade' ? 120 : 0
  const fadeOut = includeTransitionOut && style.transitionOut === 'fade' ? 120 : 0
  const fade = fadeIn || fadeOut ? `\\fad(${fadeIn},${fadeOut})` : ''
  const transition = transitionTags(style, durationMs, includeTransitionIn, includeTransitionOut)
  const header = `{\\an${alignment}\\pos(${decimal(layout.textX)},${decimal(layout.y)})\\q2\\fs${decimal(layout.fittedFontSize)}\\fsp${decimal(
    style.letterSpacing * layout.scale,
  )}${fade}${transition}}`
  const separator = '\\h'.repeat(Math.max(1, Math.min(8, Math.round(style.wordSpacing))))
  const body = layout.lines
    .map((line) =>
      line
        .map((word) => renderWord(word, style, word.id === activeWordId, layout.fittedFontSize, layout.scale, palette))
        .join(separator),
    )
    .join('\\N')

  return `${header}${body}`
}

function layoutChunk(chunk: SubtitleChunk, style: SubtitleStyle, width: number, height: number): ChunkLayout {
  const scale = height / 1080
  const maxWidth = (style.maxWidth / 100) * width
  const padding = style.backgroundMode === 'caption' ? style.boxPadding * scale : 0
  const textWidth = Math.max(width * 0.08, maxWidth - padding * 2)
  const sourceWords = chunk.words.length ? chunk.words : wordsFromText(chunk)
  const longestWord = sourceWords.reduce((longest, word) => (word.text.length > longest.length ? word.text : longest), '')
  const nominalFontSize = Math.max(10, style.fontSize * scale)
  const estimatedLongest = cleanCaptionText(longestWord, style).length * nominalFontSize * 0.61
  const fitScale = estimatedLongest > textWidth ? Math.max(0.42, textWidth / estimatedLongest) : 1
  let fittedFontSize = nominalFontSize * fitScale
  let lines = wrapWordLines(sourceWords, style, fittedFontSize, textWidth)
  for (let attempt = 0; attempt < 12 && lines.length > style.maxLines; attempt += 1) {
    fittedFontSize *= 0.9
    lines = wrapWordLines(sourceWords, style, fittedFontSize, textWidth)
  }
  const x = (style.positionX / 100) * width
  const baselineShift = style.baselineOffset * fittedFontSize
  const y = (style.positionY / 100) * height + baselineShift
  const textX = style.align === 'left' ? x - maxWidth / 2 + padding : style.align === 'right' ? x + maxWidth / 2 - padding : x
  return { scale, maxWidth, padding, fittedFontSize, lines, x, textX, y }
}

function renderCaptionBackground(chunk: SubtitleChunk, style: SubtitleStyle, width: number, height: number) {
  const layout = layoutChunk(chunk, style, width, height)
  if (style.backgroundMode === 'lines') {
    const lineHeight = layout.fittedFontSize * style.lineHeight
    const top = layout.y - (layout.lines.length * lineHeight) / 2
    const paths = layout.lines.map((line, index) => {
      const textWidth = estimateLineWidth(line, style, layout.fittedFontSize)
      const boxWidth = Math.min(layout.maxWidth, textWidth + layout.padding * 2)
      const left = style.align === 'left'
        ? layout.x - layout.maxWidth / 2
        : style.align === 'right'
          ? layout.x + layout.maxWidth / 2 - boxWidth
          : layout.x - boxWidth / 2
      const right = left + boxWidth
      const lineTop = top + index * lineHeight
      const bottom = lineTop + lineHeight
      return `m ${decimal(left)} ${decimal(lineTop)} l ${decimal(right)} ${decimal(lineTop)} ${decimal(right)} ${decimal(bottom)} ${decimal(left)} ${decimal(bottom)}`
    }).join(' ')
    return `{\\an7\\pos(0,0)\\p1\\1c${assColor(style.backgroundColor)}\\1a${assAlpha(style.backgroundOpacity)}\\bord0\\shad0}${paths}`
  }
  const boxHeight = layout.lines.length * layout.fittedFontSize * style.lineHeight + layout.padding * 2
  const left = layout.x - layout.maxWidth / 2
  const right = layout.x + layout.maxWidth / 2
  const top = layout.y - boxHeight / 2
  const bottom = layout.y + boxHeight / 2
  return `{\\an7\\pos(0,0)\\p1\\1c${assColor(style.backgroundColor)}\\1a${assAlpha(style.backgroundOpacity)}\\bord0\\shad0}m ${decimal(left)} ${decimal(top)} l ${decimal(right)} ${decimal(top)} ${decimal(right)} ${decimal(bottom)} ${decimal(left)} ${decimal(bottom)}`
}

function estimateLineWidth(line: WordLine, style: SubtitleStyle, fontSize: number) {
  const words = line.reduce((total, word) => {
    const scale = word.style?.fontScale ?? 1
    return total + Math.max(fontSize * 0.45, cleanCaptionText(word.text, style).length * fontSize * 0.53 * scale)
  }, 0)
  return words + Math.max(0, line.length - 1) * fontSize * 0.3 * Math.max(1, style.wordSpacing)
}

function renderWord(
  word: TranscriptWord,
  style: SubtitleStyle,
  active: boolean,
  fontSize: number,
  outputScale: number,
  palette: AssPalette,
) {
  const resolved = resolveWordStyle(style, word.style, active)
  const color = palette === 'mask' ? '#ffffff' : resolved.textColor
  const strokeColor = palette === 'mask' ? '#ffffff' : resolved.strokeColor
  const background = palette === 'mask' ? undefined : resolved.backgroundColor
  const activeStrokeWidth = active && !style.activeWordStroke ? 0 : resolved.strokeWidth
  const fontScale = resolved.fontScale
  const emphasisScale = active && style.wordTransition === 'pop'
    ? 112
    : active && style.wordTransition === 'zoom'
      ? 106
      : 100
  const tags = [
    `\\1c${assColor(color)}`,
    `\\3c${assColor(background && resolved.backgroundOpacity > 0 ? background : strokeColor)}`,
    `\\bord${decimal((background && resolved.backgroundOpacity > 0 ? activeStrokeWidth + 5 : activeStrokeWidth) * outputScale)}`,
    `\\shad${resolved.shadow && palette === 'normal' ? decimal(Math.max(0, style.shadowOffsetY * outputScale)) : '0'}`,
    `\\fs${decimal(fontSize * fontScale)}`,
    `\\fscx${emphasisScale}`,
    `\\fscy${emphasisScale}`,
    `\\b${resolved.fontWeight >= 700 ? '1' : '0'}`,
    `\\i${resolved.italic ? '1' : '0'}`,
    `\\u${resolved.underline ? '1' : '0'}`,
  ].join('')
  const text = assText(cleanCaptionText(word.text, style))
  return `{${tags}}${text}`
}

function wrapWordLines(words: TranscriptWord[], style: SubtitleStyle, fontSize: number, maxWidth: number): WordLine[] {
  const lines: WordLine[] = []
  let current: WordLine = []
  let currentWidth = 0
  const spaceWidth = fontSize * 0.3 * Math.max(1, style.wordSpacing)

  for (const word of words) {
    const transformed = cleanCaptionText(word.text, style)
    const weightFactor = (word.style?.fontScale ?? 1) * (word.style?.fontWeight && word.style.fontWeight >= 800 ? 1.04 : 1)
    const wordWidth = Math.max(fontSize * 0.45, transformed.length * fontSize * 0.53 * weightFactor)
    const nextWidth = currentWidth + (current.length ? spaceWidth : 0) + wordWidth
    if (current.length && nextWidth > maxWidth) {
      lines.push(current)
      current = [word]
      currentWidth = wordWidth
    } else {
      current.push(word)
      currentWidth = nextWidth
    }
  }
  if (current.length) lines.push(current)

  if (style.avoidDanglingWords && lines.length > 1) {
    const last = lines[lines.length - 1]
    const previous = lines[lines.length - 2]
    if (last.length === 1 && previous.length > 2) {
      last.unshift(previous.pop() as TranscriptWord)
    }
  }
  return lines.length ? lines : [[]]
}

function wordsFromText(chunk: SubtitleChunk): TranscriptWord[] {
  const pieces = chunk.text.split(/\s+/).filter(Boolean)
  const step = (chunk.end - chunk.start) / Math.max(1, pieces.length)
  return pieces.map((text, index) => ({
    id: `${chunk.id}-word-${index}`,
    text,
    start: chunk.start + step * index,
    end: index === pieces.length - 1 ? chunk.end : chunk.start + step * (index + 1),
  }))
}

function transitionTags(style: SubtitleStyle, durationMs: number, includeIn: boolean, includeOut: boolean) {
  const tags: string[] = []
  if (includeIn && style.transitionIn === 'zoom') tags.push('\\fscx82\\fscy82\\t(0,140,\\fscx100\\fscy100)')
  if (includeIn && style.transitionIn === 'stomp') tags.push('\\fscx128\\fscy128\\t(0,110,\\fscx100\\fscy100)')
  if (includeOut && style.transitionOut === 'zoom') {
    const start = Math.max(0, durationMs - 140)
    tags.push(`\\t(${start},${durationMs},\\fscx82\\fscy82)`)
  }
  return tags.join('')
}

function eventLine(start: number, end: number, styleName: string, text: string, layer = 1) {
  return `Dialogue: ${layer},${assTime(start)},${assTime(end)},${styleName},,0,0,0,,${text}`
}

function assTime(seconds: number) {
  const safe = Math.max(0, seconds)
  const hours = Math.floor(safe / 3600)
  const minutes = Math.floor((safe % 3600) / 60)
  const secs = Math.floor(safe % 60)
  const centis = Math.min(99, Math.round((safe - Math.floor(safe)) * 100))
  return `${hours}:${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(centis).padStart(2, '0')}`
}

function assText(value: string) {
  return value.replace(/\\/g, '\\u005c').replace(/{/g, '\\{').replace(/}/g, '\\}')
}

function assColor(hex: string, alpha = 0) {
  const normalized = normalizeHex(hex)
  const r = normalized.slice(0, 2)
  const g = normalized.slice(2, 4)
  const b = normalized.slice(4, 6)
  const a = Math.round(Math.min(1, Math.max(0, alpha)) * 255)
  return `&H${a.toString(16).padStart(2, '0')}${b}${g}${r}&`.toUpperCase()
}

function assAlpha(opacity: number) {
  const alpha = Math.round((1 - Math.min(1, Math.max(0, opacity))) * 255)
  return `&H${alpha.toString(16).padStart(2, '0')}&`.toUpperCase()
}

function normalizeHex(hex: string) {
  const raw = hex.replace('#', '').trim()
  if (/^[0-9a-f]{6}$/i.test(raw)) return raw
  if (/^[0-9a-f]{3}$/i.test(raw)) return raw.split('').map((part) => part + part).join('')
  return 'FFFFFF'
}

function assStyleName(name: string, index: number) {
  const cleaned = name.replace(/[^a-z0-9_-]+/gi, '').slice(0, 24)
  return cleaned || `Variant${index}`
}

function assFont(fontFamily: string) {
  return fontFamily.split(',')[0].replace(/["']/g, '').trim() || 'Arial'
}

function decimal(value: number) {
  return String(Math.round(value * 100) / 100)
}

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value))
}

function evenDimension(value: number) {
  const rounded = Math.max(2, Math.round(value))
  return rounded % 2 === 0 ? rounded : rounded - 1
}
