import type {
  CanvasSettings,
  CaptionVariant,
  ExportSettings,
  ModelKey,
  SubtitleStyle,
  TranscriptionSettings,
} from '../types'

export const MODEL_CONFIGS: Record<
  ModelKey,
  {
    key: ModelKey
    label: string
    modelId: string
    description: string
    sizeMb: number
  }
> = {
  large: {
    key: 'large',
    label: 'Large v3 Turbo',
    modelId: 'onnx-community/whisper-large-v3-turbo_timestamped',
    description: 'En iyi kalite. GPU ile onerilir.',
    sizeMb: 724,
  },
  base: {
    key: 'base',
    label: 'Base',
    modelId: 'onnx-community/whisper-base_timestamped',
    description: 'Daha hizli ve daha az bellek kullanir.',
    sizeMb: 396,
  },
}

const whisperLanguages = [
  ['auto', 'Otomatik algila'],
  ['turkish', 'Turkce'],
  ['english', 'English'],
  ['german', 'Deutsch'],
  ['french', 'Francais'],
  ['spanish', 'Espanol'],
  ['italian', 'Italiano'],
  ['portuguese', 'Portugues'],
  ['arabic', 'Arabic'],
  ['russian', 'Russian'],
  ['chinese', 'Chinese'],
  ['japanese', 'Japanese'],
  ['korean', 'Korean'],
  ['dutch', 'Dutch'],
  ['polish', 'Polish'],
  ['ukrainian', 'Ukrainian'],
  ['greek', 'Greek'],
  ['hebrew', 'Hebrew'],
  ['hindi', 'Hindi'],
  ['indonesian', 'Indonesian'],
  ['malay', 'Malay'],
  ['thai', 'Thai'],
  ['vietnamese', 'Vietnamese'],
  ['swedish', 'Swedish'],
  ['norwegian', 'Norwegian'],
  ['danish', 'Danish'],
  ['finnish', 'Finnish'],
  ['czech', 'Czech'],
  ['romanian', 'Romanian'],
  ['hungarian', 'Hungarian'],
  ['bulgarian', 'Bulgarian'],
  ['croatian', 'Croatian'],
  ['serbian', 'Serbian'],
  ['slovak', 'Slovak'],
  ['slovenian', 'Slovenian'],
  ['persian', 'Persian'],
  ['urdu', 'Urdu'],
  ['bengali', 'Bengali'],
  ['tamil', 'Tamil'],
  ['telugu', 'Telugu'],
  ['marathi', 'Marathi'],
  ['gujarati', 'Gujarati'],
  ['punjabi', 'Punjabi'],
  ['nepali', 'Nepali'],
  ['sinhala', 'Sinhala'],
  ['swahili', 'Swahili'],
  ['afrikaans', 'Afrikaans'],
  ['albanian', 'Albanian'],
  ['amharic', 'Amharic'],
  ['armenian', 'Armenian'],
  ['assamese', 'Assamese'],
  ['azerbaijani', 'Azerbaijani'],
  ['bashkir', 'Bashkir'],
  ['basque', 'Basque'],
  ['belarusian', 'Belarusian'],
  ['bosnian', 'Bosnian'],
  ['breton', 'Breton'],
  ['burmese', 'Burmese'],
  ['cantonese', 'Cantonese'],
  ['catalan', 'Catalan'],
  ['estonian', 'Estonian'],
  ['faroese', 'Faroese'],
  ['galician', 'Galician'],
  ['georgian', 'Georgian'],
  ['haitian creole', 'Haitian Creole'],
  ['hausa', 'Hausa'],
  ['hawaiian', 'Hawaiian'],
  ['icelandic', 'Icelandic'],
  ['javanese', 'Javanese'],
  ['kannada', 'Kannada'],
  ['kazakh', 'Kazakh'],
  ['khmer', 'Khmer'],
  ['lao', 'Lao'],
  ['latin', 'Latin'],
  ['latvian', 'Latvian'],
  ['lingala', 'Lingala'],
  ['lithuanian', 'Lithuanian'],
  ['luxembourgish', 'Luxembourgish'],
  ['macedonian', 'Macedonian'],
  ['malagasy', 'Malagasy'],
  ['malayalam', 'Malayalam'],
  ['maltese', 'Maltese'],
  ['maori', 'Maori'],
  ['mongolian', 'Mongolian'],
  ['occitan', 'Occitan'],
  ['pashto', 'Pashto'],
  ['sanskrit', 'Sanskrit'],
  ['shona', 'Shona'],
  ['sindhi', 'Sindhi'],
  ['somali', 'Somali'],
  ['sundanese', 'Sundanese'],
  ['tagalog', 'Tagalog'],
  ['tajik', 'Tajik'],
  ['tatar', 'Tatar'],
  ['tibetan', 'Tibetan'],
  ['turkmen', 'Turkmen'],
  ['uzbek', 'Uzbek'],
  ['welsh', 'Welsh'],
  ['yiddish', 'Yiddish'],
  ['yoruba', 'Yoruba'],
] as const

export const LANGUAGE_OPTIONS = whisperLanguages.map(([value, label]) => ({ value, label }))

export const BASE_STYLE: SubtitleStyle = {
  presetName: 'Candy',
  fontFamily: 'Arial Black',
  fontSize: 64,
  fontWeight: 900,
  italic: false,
  textColor: '#ffffff',
  activeColor: '#2efff6',
  strokeColor: '#050507',
  strokeWidth: 8,
  shadow: true,
  shadowColor: '#000000',
  shadowBlur: 8,
  shadowOffsetX: 0,
  shadowOffsetY: 4,
  backgroundMode: 'none',
  backgroundColor: '#000000',
  backgroundOpacity: 0.82,
  boxPadding: 16,
  borderRadius: 4,
  positionX: 50,
  positionY: 78,
  maxWidth: 72,
  align: 'center',
  verticalAlign: 'bottom',
  letterSpacing: 0,
  wordSpacing: 1,
  lineHeight: 1.05,
  maxLines: 2,
  baselineOffset: 0,
  textTransform: 'uppercase',
  removePunctuation: false,
  hiddenPunctuation: '.,!?;:',
  avoidDanglingWords: true,
  highlightActiveWord: true,
  activeWordBackground: false,
  activeWordBackgroundColor: '#2efff6',
  activeWordStroke: true,
  activeWordShadow: true,
  transitionIn: 'stomp',
  transitionOut: 'none',
  wordTransition: 'pop',
}

function makePreset(presetName: string, overrides: Partial<SubtitleStyle>): SubtitleStyle {
  return { ...BASE_STYLE, ...overrides, presetName }
}

export const STYLE_PRESETS: SubtitleStyle[] = [
  makePreset('Candy', {}),
  makePreset('Grinch', {
    fontFamily: 'Impact',
    activeColor: '#40ff37',
    strokeColor: '#050505',
    fontSize: 70,
    wordTransition: 'zoom',
  }),
  makePreset('Outline', {
    fontFamily: 'Arial',
    fontSize: 66,
    fontWeight: 800,
    textColor: '#ffffff',
    activeColor: '#ffffff',
    strokeColor: '#161922',
    strokeWidth: 4,
    shadow: false,
    transitionIn: 'fade',
    wordTransition: 'none',
  }),
  makePreset('Subtle', {
    fontFamily: 'Segoe UI',
    fontSize: 48,
    fontWeight: 700,
    activeColor: '#ffd166',
    strokeWidth: 3,
    shadowBlur: 12,
    textTransform: 'none',
    transitionIn: 'fade',
    wordTransition: 'fade',
  }),
  makePreset('Hormozi', {
    fontFamily: 'Arial Black',
    fontSize: 72,
    activeColor: '#ffe600',
    strokeWidth: 10,
    maxWidth: 82,
    transitionIn: 'zoom',
  }),
  makePreset('Creator Green', {
    fontFamily: 'Impact',
    fontSize: 68,
    activeColor: '#22e36f',
    strokeColor: '#07150d',
    strokeWidth: 9,
    maxWidth: 80,
  }),
  makePreset('Newsroom', {
    fontFamily: 'Georgia',
    fontSize: 52,
    fontWeight: 700,
    activeColor: '#ff3b30',
    strokeWidth: 2,
    backgroundMode: 'caption',
    backgroundColor: '#101114',
    backgroundOpacity: 0.9,
    textTransform: 'none',
    transitionIn: 'fade',
    wordTransition: 'none',
  }),
  makePreset('Clean Box', {
    fontFamily: 'Segoe UI',
    fontSize: 50,
    fontWeight: 700,
    textColor: '#111318',
    activeColor: '#0057ff',
    strokeWidth: 0,
    shadow: false,
    backgroundMode: 'caption',
    backgroundColor: '#ffffff',
    backgroundOpacity: 0.94,
    borderRadius: 2,
    textTransform: 'none',
    transitionIn: 'fade',
  }),
  makePreset('Neon Night', {
    fontFamily: 'Verdana',
    fontSize: 58,
    activeColor: '#00f5d4',
    strokeColor: '#2a0944',
    strokeWidth: 7,
    shadowColor: '#00f5d4',
    shadowBlur: 16,
    transitionIn: 'zoom',
  }),
  makePreset('Podcast Pink', {
    fontFamily: 'Trebuchet MS',
    fontSize: 58,
    activeColor: '#ff4fa3',
    strokeColor: '#250716',
    textTransform: 'none',
    wordTransition: 'fade',
  }),
  makePreset('Cinema', {
    fontFamily: 'Georgia',
    fontSize: 50,
    fontWeight: 700,
    textColor: '#fffaf0',
    activeColor: '#e8c46a',
    strokeColor: '#000000',
    strokeWidth: 3,
    positionY: 88,
    maxWidth: 86,
    textTransform: 'none',
    transitionIn: 'fade',
    transitionOut: 'fade',
    wordTransition: 'none',
  }),
  makePreset('Mono Tech', {
    fontFamily: 'Consolas',
    fontSize: 52,
    fontWeight: 700,
    activeColor: '#62d9ff',
    strokeColor: '#06161d',
    backgroundMode: 'caption',
    backgroundColor: '#071017',
    backgroundOpacity: 0.82,
    textTransform: 'none',
    letterSpacing: 1.4,
    transitionIn: 'fade',
  }),
  makePreset('Orange Punch', {
    fontFamily: 'Arial Black',
    fontSize: 68,
    activeColor: '#ff8a00',
    strokeColor: '#1b0c00',
    strokeWidth: 9,
    transitionIn: 'stomp',
  }),
  makePreset('Blue Focus', {
    fontFamily: 'Tahoma',
    fontSize: 60,
    activeColor: '#3ea6ff',
    strokeColor: '#07162b',
    strokeWidth: 7,
    textTransform: 'none',
    wordTransition: 'zoom',
  }),
  makePreset('Karaoke Red', {
    fontFamily: 'Arial',
    fontSize: 62,
    activeColor: '#ff2d55',
    strokeColor: '#1b0208',
    strokeWidth: 8,
    transitionIn: 'none',
    wordTransition: 'pop',
  }),
  makePreset('Minimal Lower', {
    fontFamily: 'Segoe UI',
    fontSize: 44,
    fontWeight: 600,
    activeColor: '#ffffff',
    strokeWidth: 0,
    shadowBlur: 14,
    positionY: 86,
    textTransform: 'none',
    transitionIn: 'fade',
    wordTransition: 'none',
  }),
  makePreset('Black Bar', {
    fontFamily: 'Arial',
    fontSize: 54,
    fontWeight: 700,
    activeColor: '#ffd60a',
    strokeWidth: 0,
    shadow: false,
    backgroundMode: 'caption',
    backgroundColor: '#000000',
    backgroundOpacity: 0.92,
    borderRadius: 0,
    textTransform: 'none',
  }),
  makePreset('Classic Broadcast', {
    fontFamily: 'Arial',
    fontSize: 50,
    fontWeight: 700,
    activeColor: '#ffffff',
    strokeColor: '#000000',
    strokeWidth: 5,
    positionY: 90,
    maxWidth: 88,
    textTransform: 'none',
    highlightActiveWord: false,
    transitionIn: 'none',
    wordTransition: 'none',
  }),
]

export const DEFAULT_SETTINGS: TranscriptionSettings = {
  language: 'turkish',
  modelKey: 'large',
  autoTranscribe: true,
  chunkLengthSeconds: 30,
  strideSeconds: 5,
  maxWordsPerCaption: 7,
  maxCaptionDuration: 4.5,
}

export const DEFAULT_CANVAS: CanvasSettings = {
  aspectRatio: 'source',
  scaleMode: 'contain',
  backgroundColor: '#08090d',
  showSafeZone: false,
  safeZonePlatform: 'tiktok',
  showWaveform: true,
}

export const DEFAULT_EXPORT_SETTINGS: ExportSettings = {
  mode: 'burned',
  container: 'source',
  resolution: 'source',
  frameRate: 'source',
  customWidth: 1920,
  customHeight: 1080,
  customFps: 30,
  codec: 'auto',
  compression: 45,
  quality: 90,
  speed: 'balanced',
  audio: 'high',
  audioVolume: 100,
  audioNormalize: false,
  audioFadeIn: 0,
  audioFadeOut: 0,
}

export const DEFAULT_STYLE = STYLE_PRESETS[0]

export const DEFAULT_VARIANTS: CaptionVariant[] = [
  { id: 'main', name: 'Main', style: STYLE_PRESETS[0] },
  { id: 'accent', name: 'Accent', style: STYLE_PRESETS[4] },
  { id: 'quiet', name: 'Quiet', style: STYLE_PRESETS[3] },
]

export function cloneDefaultVariants() {
  return DEFAULT_VARIANTS.map((variant) => ({ ...variant, style: { ...variant.style } }))
}

export function normalizeStyle(style?: Partial<SubtitleStyle>): SubtitleStyle {
  return { ...BASE_STYLE, ...style }
}
